config/routes.rb
Rails.application.routes.draw do

  # ホーム画面
  root 'pages#index'
  get 'users' => 'pages#show'

  devise_for :users, skip: :all

  # 認証用
  devise_scope :user do
    # セッション
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    # サインアップ
    get 'signup' => 'devise/registrations#new', as: :new_user_registration
    post 'signup' => 'devise/registrations#create', as: :user_registration
    get 'signup/cancel' => 'devise/registrations#cancel', as: :cancel_user_registration
    # 登録
    get 'user' => 'devise/registrations#edit', as: :edit_user_registration
    patch 'user' => 'devise/registrations#update', as: nil
    put 'user' => 'devise/registrations#update', as: :update_user_registration
    delete 'user' => 'devise/registrations#destroy', as: :destroy_user_registration
    #パスワード
    get 'password' => 'devise/passwords#new', as: :new_user_password
    post 'password' => 'devise/passwords#create', as: :user_password
    get 'password/edit' => 'devise/passwords#edit', as: :edit_user_password
    patch 'password' => 'devise/passwords#update'
    put 'password' => 'devise/passwords#update', as: :update_user_password
  end

  # ユーザー画面
  resources :users, param: :userid, path: '/', only: [:show] do
    member do
      get :following, :followers
    end
  end

  # 投稿用
  resources :microposts, only: [:create, :destroy]

  # フォロー
  resources :relationships, only: [:create, :destroy]

  # お気に入り
  resources :microposts do
    resources :likes, only: [:create, :destroy]
  end

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :likes, dependent: :destroy
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true,
    length: { maximum: 140 }
  def like_user(userid)
    likes.find_by(userid: userid)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  before_action :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      redirect_to root_url
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private
  def micropost_params
    params.require(:micropost).permit(:content, :image)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_like.html.erb
<% if user_signed_in? %>
  <% if micropost.like_user(current_user.id) %>
    <%= button_to micropost_like_path(micropost.id,micropost_id: micropost.id), method: :delete, id: "like-button", remote: true do %>
      ★
    <% end %>
  <% else %>
    <%= button_to micropost_likes_path(micropost_id: micropost.id), id: "like-button", remote: true do %>
      ☆
    <% end %>
  <% end %>
<% end %>

app/views/microposts/_micropost.html.erb
<div class="column is-one-third">
  <div class="card">
    <div class="header">
      <div class="media">
        <div class="media-left">
          <figure class="image is-48x48">
            <% if micropost.user.profileimage %>
              <%= image_tag micropost.user.profileimage %>
            <% else %>
              <img src="https://source.unsplash.com/random/96x96" alt="Placeholder image">
            <% end %>
          </figure>
        </div>
        <div class="media-content">
          <p class="title is-4"><%= micropost.user.username %></p>
          <p class="subtitle is-6">@<%= link_to micropost.user.userid  ,user_path(micropost.user.userid)%></p>
        </div>
      </div>
    </div>
    <div class="card-image">
      <figure class="image is-4by3">
        <% if micropost.image.url %>
          <%= image_tag micropost.image %>
        <% else %>
          <img src="https://source.unsplash.com/random/1280x960" alt="">
        <% end %>
      </figure>
    </div>
    <div class="card-content">
      <div class="level is-mobile">
        <div class="level-left">
          <div class="level-item has-text-centered">
            <%= render 'microposts/like', micropost: micropost %>
          </div>
        </div>
      </div>
      <div class="content">
        <p>

        <% if micropost.likes_count %>
          <strong><%= micropost.likes_count %> likes</strong></p>
      <% else %>
        <strong>0 Likes</strong>
      <% end %>
      </p>
      <%= micropost.content %>
      <br>
      <time>(<%= time_ago_in_words(micropost.created_at) %>)</time>
      </div>
    </div>
    <% if user_signed_in? %>
      <% if current_user.id==micropost.user.id %>
        <%= link_to "delete", micropost, method: :delete, data: { confirm: "You sure?" } %>
      <% end %>
    <% end %>
    <div class="card-footer">
      <div class="columns is-mobile">
        <div class="column is-11">
          <div class="field">
            <div class="control">
              <input class="input is-medium" type="text" placeholder="Add a comment . . .">
            </div>
          </div>
        </div>
        <div class="column has-text-centered">
          <button class="button">
            <i class="material-icons">★</i>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>